//Base code project for CMP1903M Assessment 1
namespace CMP1903M_Assessment_1_Base_Code
{
    class Program
    {
        static void Main()
        {
            //Create input object
            //Create analyse object
            //Create report object

            Input input = new();
            Analyse analyse = new();
            Report report = new();

            //Define response string
            string? response;

            //Define text string, this will be filled with either the users input or the text from a file
            string text;

            //Define parameters list
            List<int> parameters;

            string message = "Please ensure 'CMP1903M Assessment 1 Test File.txt' is in the bin folder.";

            Console.WriteLine(message);
            Console.WriteLine();

            //Define a boolean for the while loop
            bool isLoop = true;

            //While loop keeps the application open until a valid function has been performed
            while (isLoop)
            {
                //Ask the user which function they would like to perform
                Console.WriteLine("1. Do you want to enter the text via the keyboard?");
                Console.WriteLine("2. Do you want to read in the text from a file?");

                //Sets the response variable to the user-inputted response
                response = Console.ReadLine();

                //Checks the value of the response variable
                if (response == "1")
                {
                    //Runs the manual text input function from the Input class
                    text = input.ManualTextInput();

                    //Sets the values in the parameters list to the values generated by analysing the text in the Analyse class
                    parameters = analyse.AnalyseText(text);

                    //Outputs the values of the parameters list using the Report class
                    report.OutputConsole(parameters);

                    //Ends the loop
                    isLoop = false;
                }
                else if (response == "2")
                {
                    //Sets the file name
                    string file = "CMP1903M Assessment 1 Test File.txt";

                    //Sets the text variable to the text in the file using the Input class
                    text = input.FileTextInput(file);

                    //Outputs the text in the file to the console
                    Console.WriteLine(text);

                    //Sets the values in the parameters list to the values generated by analysing the text in the Analyse class
                    parameters = analyse.AnalyseText(text);

                    //Outputs the values of the parameters list using the Report class
                    report.OutputConsole(parameters);

                    //Ends the loop
                    isLoop = false;
                }
                else
                {
                    //If the user-inputted response is invalid, output error message and restart loop
                    Console.WriteLine("Invalid response.");
                }
            }
        }
    }
}
